### ISSUE TITLE
JSON response does not process positions

### ISSUE THREAD

**Issue by kapilnarula** [tuantvu/flutter_linkedin_login#18]
The API call to linkedin retrieves the positions data.

private val URL = "https://api.linkedin.com/v1/people/~:(id,first-name,last-name," +
"headline,industry,summary,picture-url,email-address,formatted-name,location,specialties,positions)?format=json"

Position data in JSON contains information about the individual's last company like name, location, startDateYear, startDateMonth, Title, Summary, isCurrent.

However, this information is not retrieved and returned by the getProfile() function. It would be great if this can be provided as well.

**Comment by tuantvu** [comment]
@kapilnarula Thanks for the issue submission, I will start looking into this. But if you would like to fork and do a pull request to add this functionality, I'd be happy to review and test, then merge

**Comment by tuantvu** [comment]
@kapilnarula I've added positions object to LinkedInProfile. Please check it out. I'll close the issue for now, but you can reopen if it does not satisfy your needs.

**Comment by narulakapil** [comment]
@tuantvu Thanks a lot for your quick response. The fix is proper but just a minor issue though. There are two fields in json that should be processed. They are:
1. publicProfileUrl
2. companyLocation in positions

A sample JSON response that I got from LinkedIn is posted below.
{
  "emailAddress"=>"xxxxx.xxxx@gmail.com", 
  "firstName"=>"Kapil", 
  "headline"=>"Business", 
  "id"=>"xdL70zZCeB", 
  "industry"=>"Information Services", 
  "lastName"=>"Narula", 
  "location"=> {
    "country"=> {
      "code"=>"in"
    }, 
    "name"=>"Kanpur, India"
  }, 
  "numConnections"=>70, 
  "positions"=>{
    "_total"=>1, 
    "values"=>[
      {
        "company"=>{
          "name"=>"Narulas Food Products"
        }, 
        "id"=>509073958, 
        "isCurrent"=>true, 
        "location"=>{
          "country"=>{
            "code"=>"in", 
            "name"=>"India"
          }, 
          "name"=>"Lucknow Area, India"
        }, 
        "startDate"=>{
          "month"=>12, 
          "year"=>2009
        }, 
        "summary"=>"I manage the business operations of my family owned enterprise in Lucknow. ", 
        "title"=>"Managing Partner"
      }
    ]
  }, 
  "publicProfileUrl"=>"http://www.linkedin.com/in/kapil-narula-3217191"
}

**Comment by narulakapil** [comment]
I used the following LinkedIn API Url:
https://api.linkedin.com/v1/people/~:(id,num-connections,picture-url,picture-urls::(original),first-name,last-name,headline,location,industry,summary,specialties,positions,public-profile-url,email-address)?format=json
