### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by arn3la** [tuantvu/flutter_linkedin_login#21]
@tuantvu Hi again. 

Is there any way that I can fetch access token after sign in?

**Comment by tuantvu** [comment]
@arn3la @d3xt3r2909 Completed for Android. Need to borrow a MacBook to test on iOS. Will release by end of weekend

**Comment by tuantvu** [comment]
@arn3la @d3xt3r2909 accessToken available for Android. I couldn't test on iOS 12, due to LinkedIn app no longer responding to sign in request from 3rd party apps. I found this on their blog: https://engineering.linkedin.com/blog/2018/12/developer-program-updates. I've updated the Readme warning of this plugin no longer working on March 2019.

**Comment by d3xt3r2909** [comment]
> @arn3la @d3xt3r2909 accessToken available for Android. I couldn't test on iOS 12, due to LinkedIn app no longer responding to sign in request from 3rd party apps. I found this on their blog: https://engineering.linkedin.com/blog/2018/12/developer-program-updates. I've updated the Readme warning of this plugin no longer working on March 2019.

Hello @tuantvu, I have implemented a new library, so if you want you can put a link to my library. This library is working with version 2 of LinkedIn. Feel free to share your knowledge or to open issues. 

https://pub.dartlang.org/packages/linkedin_login
